version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: pixswap-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: pixswap
    volumes:
      - mongodb_dev_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - pixswap-dev-network

  # Redis for Socket.IO scaling (optional)
  redis:
    image: redis:7-alpine
    container_name: pixswap-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    networks:
      - pixswap-dev-network

volumes:
  mongodb_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  pixswap-dev-network:
    driver: bridge